services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carekobooks-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_KEYCLOAK_URL: ${NEXT_PUBLIC_KEYCLOAK_URL}
      NEXT_PUBLIC_KEYCLOAK_REALM: ${NEXT_PUBLIC_KEYCLOAK_REALM}
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: ${NEXT_PUBLIC_KEYCLOAK_CLIENT_ID}
      NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
    restart: unless-stopped
