services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_API_WEBSOCKET_URL: ${NEXT_PUBLIC_API_WEBSOCKET_URL}
        NEXT_PUBLIC_S3_HOSTNAME: ${NEXT_PUBLIC_S3_HOSTNAME}
        NEXT_PUBLIC_KEYCLOAK_URL: ${NEXT_PUBLIC_KEYCLOAK_URL}
        NEXT_PUBLIC_KEYCLOAK_REALM: ${NEXT_PUBLIC_KEYCLOAK_REALM}
        NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: ${NEXT_PUBLIC_KEYCLOAK_CLIENT_ID}
    container_name: carekobooks-frontend
    ports:
      - "3000:3000"
