name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: carekenvironment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_API_WEBSOCKET_URL: ${{ secrets.NEXT_PUBLIC_API_WEBSOCKET_URL }}
          NEXT_PUBLIC_S3_HOSTNAME: ${{ secrets.NEXT_PUBLIC_S3_HOSTNAME }}
          NEXT_PUBLIC_KEYCLOAK_URL: ${{ secrets.NEXT_PUBLIC_KEYCLOAK_URL }}
          NEXT_PUBLIC_KEYCLOAK_REALM: ${{ secrets.NEXT_PUBLIC_KEYCLOAK_REALM }}
          NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID }}
        working-directory: careko-books
        run: docker compose -f docker-compose.staging.yml up -d --build --force-recreate 
